### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Magiguigui** [ChemaAlfonso/neumorph.scss#2]
Hello nice job, it's really well done !
Have you planed to improve bootstrap compatibility (nav, card, pills, etc...) ?
Am currently working on it (more trying to make it work on nav/card with existing classes but doesn't seems to be enough for the awaited result) I'll open PR if I add some usefull components

**Comment by ChemaAlfonso** [comment]
Hi Magiguigui, yes, but i haven't got enought time to improve as much as I would like to for now. Feel free to do PR, all improvements are welcome, thank you so much!
